### ISSUE TITLE
Cannot run locally - missing file in git

### ISSUE THREAD

**Issue by Ninban** [GabLeRoux/webextensions-history-browser#13]
Followed the instructions to run the project locally, but the following error is thrown.
It seems the source is missing the `./icons/history-32.png` file.
Removing the code referencing this file makes it compile correctly.

```
ERROR in ./src/history.html (./node_modules/html-webpack-plugin/lib/loader.js!./src/history.html)
    Module not found: Error: Can't resolve './icons/history-32.png' in '/Users/carlouellette/git/webextensions-history-browser/src'
     @ ./src/history.html (./node_modules/html-webpack-plugin/lib/loader.js!./src/history.html) 1:346-379
```

**Comment by GabLeRoux** [comment]
oh that’s my bad, lost it in previous refactor, was probably working in my case due to the file being in an ignored folder or something like that. the missing file can be found in the repo in the previous tag. We should only place it back to fix it.

I’m not near my laptop now so feel free to send a pr, otherwise, I’ll fix this later tonight. Thanks :)
